"""Added device_type to Airdrop model

Revision ID: b8e1903b11ea
Revises: 
Create Date: 2025-03-25 09:36:47.108901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8e1903b11ea'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airdrops',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('image_url', sa.String(length=250), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('chain', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('device_type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('upload_date', sa.DateTime(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('rating_value', sa.Float(), nullable=True),
    sa.Column('project_socials', sa.JSON(), nullable=True),
    sa.Column('amount_raised', sa.Float(), nullable=True),
    sa.Column('completion_percent', sa.Integer(), nullable=False),
    sa.Column('expected_tge_date', sa.DateTime(), nullable=False),
    sa.Column('airdrop_start_date', sa.DateTime(), nullable=False),
    sa.Column('airdrop_end_date', sa.DateTime(), nullable=False),
    sa.Column('is_tracked', sa.Boolean(), nullable=True),
    sa.Column('expected_distribution_token', sa.String(), nullable=True),
    sa.Column('external_tracking_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('referral_code', sa.String(length=10), nullable=False),
    sa.Column('referred_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['referred_by'], ['users.referral_code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('referral_code'),
    sa.UniqueConstraint('username')
    )
    op.create_table('airdrop_ratings',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('airdrop_id', sa.Integer(), nullable=False),
    sa.Column('rating_value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['airdrop_id'], ['airdrops.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'airdrop_id')
    )
    op.create_table('airdrop_steps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('airdrop_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('screenshot_url', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['airdrop_id'], ['airdrops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('airdrop_tracking',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('airdrop_id', sa.Integer(), nullable=False),
    sa.Column('completed_steps', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['airdrop_id'], ['airdrops.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'airdrop_id')
    )
    op.create_table('timers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('airdrop_id', sa.Integer(), nullable=False),
    sa.Column('reminder_interval', sa.Integer(), nullable=False),
    sa.Column('next_reminder_time', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['airdrop_id'], ['airdrops.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timers_id'), 'timers', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timers_id'), table_name='timers')
    op.drop_table('timers')
    op.drop_table('airdrop_tracking')
    op.drop_table('airdrop_steps')
    op.drop_table('airdrop_ratings')
    op.drop_table('users')
    op.drop_table('airdrops')
    # ### end Alembic commands ###
