"""added funding field

Revision ID: 072b5219ca2f
Revises: 53d438f48575
Create Date: 2025-03-29 20:53:44.023896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '072b5219ca2f'
down_revision: Union[str, None] = '53d438f48575'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('airdrops', sa.Column('funding', sa.Float(), nullable=True))
    op.drop_column('airdrops', 'amount_raised')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('airdrops', sa.Column('amount_raised', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('airdrops', 'funding')
    # ### end Alembic commands ###
