"""update

Revision ID: 1ef1ab5fc295
Revises: 4811445ea760
Create Date: 2025-04-21 20:53:46.163610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ef1ab5fc295'
down_revision: Union[str, None] = '4811445ea760'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('level', sa.Integer(), nullable=True))
    op.drop_column('users', 'user_level')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_level', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('users', 'level')
    # ### end Alembic commands ###
