"""added cost_to_complete

Revision ID: 2f2cddf81a23
Revises: 2a6c668ccc35
Create Date: 2025-04-09 18:54:33.809087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f2cddf81a23'
down_revision: Union[str, None] = '2a6c668ccc35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('airdrops', sa.Column('cost_to_complete', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('airdrops', 'cost_to_complete')
    # ### end Alembic commands ###
