"""added funding field

Revision ID: 626f9d43dceb
Revises: 072b5219ca2f
Create Date: 2025-03-29 20:56:18.063032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '626f9d43dceb'
down_revision: Union[str, None] = '072b5219ca2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('airdrops', sa.Column('expected_token_ticker', sa.String(), nullable=True))
    op.drop_column('airdrops', 'expected_distribution_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('airdrops', sa.Column('expected_distribution_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('airdrops', 'expected_token_ticker')
    # ### end Alembic commands ###
