"""changed model name

Revision ID: 6756dd20d667
Revises: 9e3829e5011c
Create Date: 2025-04-07 01:50:29.010651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6756dd20d667'
down_revision: Union[str, None] = '9e3829e5011c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('airdrops', sa.Column('external_airdrop_url', sa.String(), nullable=True))
    op.drop_column('airdrops', 'external_tracking_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('airdrops', sa.Column('external_tracking_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('airdrops', 'external_airdrop_url')
    # ### end Alembic commands ###
