"""update

Revision ID: b38f89ce682d
Revises: 6756dd20d667
Create Date: 2025-04-09 00:47:09.493159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b38f89ce682d'
down_revision: Union[str, None] = '6756dd20d667'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('airdrops', 'expected_tge_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('airdrops', 'airdrop_start_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('airdrops', 'airdrop_end_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('airdrops', 'airdrop_end_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('airdrops', 'airdrop_start_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('airdrops', 'expected_tge_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
