services:
  # ──────────────────── Database ────────────────────
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER_FILE: /run/secrets/pguser
      POSTGRES_PASSWORD_FILE: /run/secrets/pgpassword
      POSTGRES_DB_FILE: /run/secrets/pgdb
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$(cat /run/secrets/pguser) -d $$(cat /run/secrets/pgdb) -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    secrets:
      - pguser
      - pgpassword
      - pgdb

  # ──────────────────── Message Broker ───────────────
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"

  # ──────────────────── FastAPI Web ──────────────────
  web:
    build: .
    command: >
      /bin/bash -c "
        echo '→ inside container, cat /run/secrets/pguser:' &&
        cat /run/secrets/pguser &&
        echo '→ now running Alembic…' &&
        alembic upgrade head &&
        echo '→ Alembic done, starting uvicorn…' &&
        uvicorn server:app --host 0.0.0.0 --port 8000 --reload
      "
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      POSTGRES_USER_FILE:           /run/secrets/pguser
      POSTGRES_PASSWORD_FILE:       /run/secrets/pgpassword
      PGHOST_FILE:                  /run/secrets/pghost
      PGPORT_FILE:                  /run/secrets/pgport
      POSTGRES_DB_FILE:             /run/secrets/pgdb
      SECRET_KEY_FILE:              /run/secrets/secret_key
      ENCRYPTION_KEY_FILE:          /run/secrets/encryption_key
      FERNET_KEY_FILE:              /run/secrets/fernet_key
      DATABASE_URL_FILE:            /run/secrets/database_url
      CELERY_BROKER_URL_FILE:       /run/secrets/celery_broker_url
      CELERY_RESULT_BACKEND_FILE:   /run/secrets/celery_result_backend
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s
    secrets:
      - pguser
      - pgpassword
      - pghost
      - pgport
      - pgdb
      - secret_key
      - encryption_key
      - fernet_key
      - database_url
      - celery_broker_url
      - celery_result_backend

  # ─────────────────── Celery Worker ─────────────────
  worker:
    build: .
    command: celery -A celery_app worker --loglevel=info
    volumes:
      - .:/app
    environment:
      POSTGRES_USER_FILE:           /run/secrets/pguser
      POSTGRES_PASSWORD_FILE:       /run/secrets/pgpassword
      PGHOST_FILE:                  /run/secrets/pghost
      PGPORT_FILE:                  /run/secrets/pgport
      POSTGRES_DB_FILE:             /run/secrets/pgdb
      SECRET_KEY_FILE:              /run/secrets/secret_key
      ENCRYPTION_KEY_FILE:          /run/secrets/encryption_key
      FERNET_KEY_FILE:              /run/secrets/fernet_key
      DATABASE_URL_FILE:            /run/secrets/database_url
      CELERY_BROKER_URL_FILE:       /run/secrets/celery_broker_url
      CELERY_RESULT_BACKEND_FILE:   /run/secrets/celery_result_backend
    depends_on:
      - db
      - redis
    secrets:
      - pguser
      - pgpassword
      - pghost
      - pgport
      - pgdb
      - secret_key
      - encryption_key
      - fernet_key
      - database_url
      - celery_broker_url
      - celery_result_backend

  # ──────────────── Celery Beat (Scheduler) ───────────
  beat:
    build: .
    command: celery -A celery_app beat --loglevel=info --schedule=/tmp/celerybeat-schedule
    volumes:
      - .:/app
      - /tmp:/tmp
    environment:
      POSTGRES_USER_FILE:           /run/secrets/pguser
      POSTGRES_PASSWORD_FILE:       /run/secrets/pgpassword
      PGHOST_FILE:                  /run/secrets/pghost
      PGPORT_FILE:                  /run/secrets/pgport
      POSTGRES_DB_FILE:             /run/secrets/pgdb
      SECRET_KEY_FILE:              /run/secrets/secret_key
      ENCRYPTION_KEY_FILE:          /run/secrets/encryption_key
      FERNET_KEY_FILE:              /run/secrets/fernet_key
      DATABASE_URL_FILE:            /run/secrets/database_url
      CELERY_BROKER_URL_FILE:       /run/secrets/celery_broker_url
      CELERY_RESULT_BACKEND_FILE:   /run/secrets/celery_result_backend
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    secrets:
      - pguser
      - pgpassword
      - pghost
      - pgport
      - pgdb
      - secret_key
      - encryption_key
      - fernet_key
      - database_url
      - celery_broker_url
      - celery_result_backend

volumes:
  db_data:

secrets:
  pguser:
    file: ./secrets/pguser
  pgpassword:
    file: ./secrets/pgpassword
  pghost:
    file: ./secrets/pghost
  pgport:
    file: ./secrets/pgport
  pgdb:
    file: ./secrets/pgdb
  secret_key:
    file: ./secrets/secret_key
  encryption_key:
    file: ./secrets/encryption_key
  fernet_key:
    file: ./secrets/fernet_key
  database_url:
    file: ./secrets/database_url
  celery_broker_url:
    file: ./secrets/celery_broker_url
  celery_result_backend:
    file: ./secrets/celery_result_backend
