"""initial

Revision ID: 5e183ca90328
Revises: 68e90536f9db
Create Date: 2025-07-16 10:24:21.493076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e183ca90328'
down_revision: Union[str, None] = '68e90536f9db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('image_url', sa.String(length=250), nullable=False))
    op.add_column('submissions', sa.Column('cost_to_complete', sa.Integer(), nullable=True))
    op.add_column('submissions', sa.Column('project_socials', sa.JSON(), nullable=True))
    op.add_column('submissions', sa.Column('funding', sa.Float(), nullable=True))
    op.add_column('submissions', sa.Column('referral_link', sa.String(), nullable=True))
    op.add_column('submissions', sa.Column('rating_value', sa.Float(), nullable=False))
    op.add_column('submissions', sa.Column('airdrop_start_date', sa.DateTime(), nullable=True))
    op.add_column('submissions', sa.Column('airdrop_end_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'airdrop_end_date')
    op.drop_column('submissions', 'airdrop_start_date')
    op.drop_column('submissions', 'rating_value')
    op.drop_column('submissions', 'referral_link')
    op.drop_column('submissions', 'funding')
    op.drop_column('submissions', 'project_socials')
    op.drop_column('submissions', 'cost_to_complete')
    op.drop_column('submissions', 'image_url')
    # ### end Alembic commands ###
