"""Fix FCM token user_id type and update airdrop_steps

Revision ID: 95d49604810e
Revises: 997fc6a0aced
Create Date: 2025-08-04 12:39:50.242166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95d49604810e'
down_revision: Union[str, None] = '997fc6a0aced'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fcm_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('airdrop_steps', sa.Column('airdrop_id', sa.Integer(), nullable=True))
    op.add_column('airdrop_steps', sa.Column('step_number', sa.Integer(), nullable=False))
    op.add_column('airdrop_steps', sa.Column('title', sa.String(), nullable=False))
    op.add_column('airdrop_steps', sa.Column('instructions', sa.JSON(), nullable=False))
    op.add_column('airdrop_steps', sa.Column('image_url', sa.String(), nullable=True))
    op.create_index(op.f('ix_airdrop_steps_id'), 'airdrop_steps', ['id'], unique=False)
    op.drop_constraint(op.f('airdrop_steps_submission_id_fkey'), 'airdrop_steps', type_='foreignkey')
    op.create_foreign_key(None, 'airdrop_steps', 'submissions', ['airdrop_id'], ['id'], ondelete='CASCADE')
    op.drop_column('airdrop_steps', 'screenshot_url')
    op.drop_column('airdrop_steps', 'description')
    op.drop_column('airdrop_steps', 'step_order')
    op.drop_column('airdrop_steps', 'submission_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('airdrop_steps', sa.Column('submission_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('airdrop_steps', sa.Column('step_order', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('airdrop_steps', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('airdrop_steps', sa.Column('screenshot_url', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'airdrop_steps', type_='foreignkey')
    op.create_foreign_key(op.f('airdrop_steps_submission_id_fkey'), 'airdrop_steps', 'submissions', ['submission_id'], ['id'])
    op.drop_index(op.f('ix_airdrop_steps_id'), table_name='airdrop_steps')
    op.drop_column('airdrop_steps', 'image_url')
    op.drop_column('airdrop_steps', 'instructions')
    op.drop_column('airdrop_steps', 'title')
    op.drop_column('airdrop_steps', 'step_number')
    op.drop_column('airdrop_steps', 'airdrop_id')
    op.drop_table('fcm_tokens')
    # ### end Alembic commands ###
