"""add unique constraint to airdrop_tracking

Revision ID: 997fc6a0aced
Revises: 5e183ca90328
Create Date: 2025-07-18 05:31:36.129798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '997fc6a0aced'
down_revision: Union[str, None] = '5e183ca90328'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_user_submission', 'airdrop_tracking', ['user_id', 'submission_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_user_submission', 'airdrop_tracking', type_='unique')
    # ### end Alembic commands ###
