"""Rename airdrop_id to submission_id

Revision ID: ecc35787cbfe
Revises: 9b077a44c4ed
Create Date: 2025-08-04 13:16:23.151432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecc35787cbfe'
down_revision: Union[str, None] = '9b077a44c4ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('airdrop_steps', sa.Column('submission_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('airdrop_steps_airdrop_id_fkey'), 'airdrop_steps', type_='foreignkey')
    op.create_foreign_key(None, 'airdrop_steps', 'submissions', ['submission_id'], ['id'], ondelete='CASCADE')
    op.drop_column('airdrop_steps', 'airdrop_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('airdrop_steps', sa.Column('airdrop_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'airdrop_steps', type_='foreignkey')
    op.create_foreign_key(op.f('airdrop_steps_airdrop_id_fkey'), 'airdrop_steps', 'submissions', ['airdrop_id'], ['id'], ondelete='CASCADE')
    op.drop_column('airdrop_steps', 'submission_id')
    # ### end Alembic commands ###
